travis: Add special check for queue processor lists matching.

diff --git a/tools/travis/production-helper b/tools/travis/production-helper
--- a/tools/travis/production-helper
+++ b/tools/travis/production-helper
@@ -83,6 +83,20 @@ if ! diff -ur /tmp/http-headers-processed ~/success-http-headers.txt; then
     exit 1
 fi
 
+# Start the RabbitMQ queue worker related section
+echo; echo "Now confirming all the RabbitMQ queue processors are correctly registered!"; echo
+# These hacky shell scripts just extract the sorted list of queue processors, running and expected
+supervisorctl status | cut -f1 -dR | cut -f2- -d: | grep events | cut -f1 -d" " | cut -f3- -d_ | cut -f1 -d- | sort -u > /tmp/running_queue_processors.txt
+for i in `/home/zulip/deployments/current/scripts/lib/queue_workers.py`; do echo $i | grep -v ^test$; done | sort > /tmp/expected_queue_processors.txt
+if diff /tmp/expected_queue_processors.txt /tmp/running_queue_processors.txt >/dev/null; then
+    echo "FAILURE: Runnable queue processors declared in zerver/worker/queue_processors.py "
+    echo "do not match those in puppet/manifests/zulip/base.pp"
+    echo "See http://zulip.readthedocs.io/en/latest/queuing.html for details."
+    echo
+    diff -ur /tmp/expected_queue_processors.txt /tmp/running_queue_processors.txt
+    exit 1
+fi
+
 echo; echo "Now running RabbitMQ consumer Nagios tests"; echo
 # First run the check that usually runs in cron and populates the state files
 /home/zulip/deployments/current/scripts/nagios/check-rabbitmq-consumers
