Travis: Display all errors, not just first one, in py3k testing.

diff --git a/tools/travis/py3k b/tools/travis/py3k
--- a/tools/travis/py3k
+++ b/tools/travis/py3k
@@ -42,10 +42,20 @@ libpasteurize.fixes.fix_newstyle
 
 echo; echo "Testing for additions of Python 2 patterns we've removed as part of moving towards Python 3 compatibility."; echo
 
+failed=0
 for fixer in $fixers; do
     echo "Running Python 3 compatibility test $fixer"
     futurize -f $fixer -j4 -n -w . >/dev/null 2>/dev/null
-    git diff --exit-code || (echo; echo "Python 3 compatibility error(s) detected!  See diff above for what you need to change." && exit 1)
+    if ! git diff --exit-code; then
+        # Clear the output from this one
+        git reset --hard >/dev/null
+        failed=1
+    fi
 done
 
-echo "No issues detected!"
+echo
+if [ -z "$failed" ]; then
+    echo "No issues detected!"
+else
+    echo "Python 3 compatibility error(s) detected!  See diffs above for what you need to change."
+fi
