setup-static-analysis: Add wrapper to retry dependancy installation.

diff --git a/tools/travis/setup-static-analysis b/tools/travis/setup-static-analysis
--- a/tools/travis/setup-static-analysis
+++ b/tools/travis/setup-static-analysis
@@ -4,5 +4,13 @@ set -x
 
 # We only need mypy and the python 3 compatibility checkers in this
 # build, so we just install those directly, skipping provision.
-pip install --no-deps -r requirements/mypy.txt
-pip install --no-deps -r requirements/py3k.txt
+
+if ! pip install --no-deps -r requirements/mypy.txt; then
+    echo "\`pip install --no-deps -r requirements/mypy.txt\`: Failure occured while trying to perform dependancy installation, Retrying..."
+    pip install --no-deps -r requirements/mypy.txt
+fi
+
+if ! pip install --no-deps -r requirements/py3k.txt; then
+    echo "\`pip install --no-deps -r requirements/py3k.txt\`: Failure occured while trying to perform dependancy installation, Retrying..."
+    pip install --no-deps -r requirements/py3k.txt
+fi
