setup-production: Improve debugging of build-release-tarball errors.

diff --git a/tools/travis/setup-production b/tools/travis/setup-production
--- a/tools/travis/setup-production
+++ b/tools/travis/setup-production
@@ -14,7 +14,11 @@ sudo apt-get remove postgresql-9.1 postgresql-client-9.1 postgresql-9.1-postgis-
 python tools/provision.py --travis --production-travis
 cp -a tools/travis/success-http-headers.txt ~/
 source /srv/zulip-venv/bin/activate
-./tools/build-release-tarball travis
+if ! ./tools/build-release-tarball travis; then
+    echo "Attempting to output failure logging data"
+    cat /tmp/tmp.*/zulip-server-travis/update-prod-static.log || true
+    exit 1
+fi
 mv /tmp/tmp.*/zulip-server-travis.tar.gz ./
 
 # Shut down all services so that restarting postgres and rebuilding
