setup-backend: Add wrapper to retry provisioning in case it fails.
In this commit we add a wrapper around the provisioning inside
setup-backend to trigger another try at provisioning if it fails
in hopes of it will run this time fine if it was interuppted by a
network issue the first time.
Fixes: #2034.

diff --git a/tools/travis/setup-backend b/tools/travis/setup-backend
--- a/tools/travis/setup-backend
+++ b/tools/travis/setup-backend
@@ -3,7 +3,13 @@ set -e
 set -x
 
 # This is just a thin wrapper around provision.
-tools/provision --travis
+# Provisioning may fail due to many issues but most of the times a network
+# connection issue is the reason. So we are going to retry entire provisioning
+# once again if that fixes our problem.
+if ! tools/provision --travis; then
+    echo "\`provision\`: Something went wrong with the provisioning, might be a network issue, Retrying to provision..."
+    tools/provision --travis
+fi
 
 # Create nagios state so that we can test-run the Nagios checks
 # against the run-dev.py server, as a form of end-to-end test
