Changes to error handling
Improved error messaging.
Redirected error message into STDERR.
Updated the if statement to exit with an appropriate exit code.

diff --git a/scripts/setup/install b/scripts/setup/install
--- a/scripts/setup/install
+++ b/scripts/setup/install
@@ -1,8 +1,8 @@
 #!/bin/bash
 if [ "$EUID" -ne 0 ];
     then
-    echo "Error: Script is running with insufficient privileges. Please re-run using sudo."
-    exit
+    echo "Error: The installation script must be run as root" >&2
+    exit 1
 fi
 mkdir -p /var/log/zulip
 "$(dirname "$(dirname "$0")")/lib/install" "$@" 2>&1 | tee -a /var/log/zulip/install.log
