postgres-init-db: Throw an error if not run as root.
Fixes part of the dicsussion in #552.

diff --git a/scripts/setup/postgres-init-db b/scripts/setup/postgres-init-db
--- a/scripts/setup/postgres-init-db
+++ b/scripts/setup/postgres-init-db
@@ -1,5 +1,10 @@
 #!/bin/bash
 set -e
+
+if [ "$EUID" -ne 0 ]; then
+    echo "Error: This script must be run as root" >&2
+    exit 1
+fi
 set -x
 
 # What user should we use for connecting to the database
