install: Remove PostgreSQL 13 support.
PostgreSQL 13 reaches end of life on November 13, 2025, and Django 5.2
does not support it.

Signed-off-by: Anders Kaseorg <anders@zulip.com>

diff --git a/scripts/lib/install b/scripts/lib/install
--- a/scripts/lib/install
+++ b/scripts/lib/install
@@ -241,8 +241,8 @@ if [ "$EXTERNAL_HOST" = zulip.example.com ] \
 fi
 
 case "$POSTGRESQL_VERSION" in
-    [0-9] | [0-9].* | 1[0-2] | 1[0-2].*)
-        echo "error: PostgreSQL 13 or newer is required." >&2
+    [0-9] | [0-9].* | 1[0-3] | 1[0-3].*)
+        echo "error: PostgreSQL 14 or newer is required." >&2
         exit 1
         ;;
 esac
