install: Remove PostgreSQL 11 support.
Django 4.2 removes this support, so Zulip has not installed with
PostgreSQL 11 since 2c20028aa451.

diff --git a/scripts/lib/install b/scripts/lib/install
--- a/scripts/lib/install
+++ b/scripts/lib/install
@@ -176,8 +176,8 @@ if [ "$EXTERNAL_HOST" = zulip.example.com ] \
 fi
 
 case "$POSTGRESQL_VERSION" in
-    [0-9] | [0-9].* | 10 | 10.*)
-        echo "error: PostgreSQL 11 or newer is required." >&2
+    [0-9] | [0-9].* | 1[01] | 1[01].*)
+        echo "error: PostgreSQL 12 or newer is required." >&2
         exit 1
         ;;
 esac
