ci: Add test to check for untracked files.
Runs a test at the end of tools/ci/backend to check if any untracked
files have been created during this ci tests. Exits with error code 1
if untracked files are found, otherwise exits successfully.

Fixes #14691.

diff --git a/tools/ci/backend b/tools/ci/backend
--- a/tools/ci/backend
+++ b/tools/ci/backend
@@ -38,3 +38,11 @@ set -x
 # NB: Everything here should be in `tools/test-all`.  If there's a
 # reason not to run it there, it should be there as a comment
 # explaining why.
+
+# This final check looks for untracked files that may have been
+# created by test-backend or provision.
+untracked="$(git ls-files --exclude-standard --others)"
+if [ -n "$untracked" ]; then
+    printf >&2 "Error: untracked files:\n%s\n" "$untracked"
+    exit 1
+fi
