Remove Debian 10 support.
As a consequence:

• Bump minimum supported Python version to 3.8.
• Move Vagrant environment to Ubuntu 20.04, which has Python 3.8.
• Move CI frontend tests to Ubuntu 20.04.
• Move production build test to Ubuntu 20.04.
• Move 3.4 upgrade test to Ubuntu 20.04.

Signed-off-by: Anders Kaseorg <anders@zulip.com>

diff --git a/tools/provision b/tools/provision
--- a/tools/provision
+++ b/tools/provision
@@ -19,7 +19,7 @@ fi
 
 os="$(. /etc/os-release && echo "$ID $VERSION_ID")"
 case "$os" in
-    'ubuntu 14.04' | 'ubuntu 16.04' | 'ubuntu 18.04')
+    'ubuntu 14.04' | 'ubuntu 16.04' | 'ubuntu 18.04' | 'debian 10')
         echo "Error: $os is no longer a supported platform for Zulip." >&2
         if [ -e /home/vagrant ]; then
             # shellcheck disable=SC2016
@@ -32,8 +32,8 @@ esac
 
 python_version="$(python3 --version)"
 case "$python_version" in
-    Python\ 3.[0-6].*)
-        echo 'Error: Zulip requires an OS with Python 3.7 or later.' >&2
+    Python\ 3.[0-7].*)
+        echo 'Error: Zulip requires an OS with Python 3.8 or later.' >&2
         exit 1
         ;;
 esac
