push-to-pull-request: Fix shell usage in an error path.
Errors go to stderr, not stdout.

While we're here, match the message itself to the others in
this script.

diff --git a/tools/push-to-pull-request b/tools/push-to-pull-request
--- a/tools/push-to-pull-request
+++ b/tools/push-to-pull-request
@@ -69,7 +69,7 @@ pr_jq () {
 }
 
 if [ "$(pr_jq -r .message)" = "Not Found" ]; then
-    echo "Invalid PR URL: $pr_url"
+    echo "error: invalid PR URL: $pr_url" >&2
     exit 1
 fi
 
