test-migrations: Add a check to avoid auto named migrations.

diff --git a/tools/test-migrations b/tools/test-migrations
--- a/tools/test-migrations
+++ b/tools/test-migrations
@@ -1,6 +1,21 @@
 #!/bin/bash
 set -e
 echo 'Testing whether migrations are consistent with models'
+
+auto_named_migrations=$(echo $(./manage.py showmigrations | grep "auto"))
+already_auto_named_migrations=$(echo "[X] 0004_auto_20160423_0400 \
+(2 squashed migrations) [X] 0005_auto_20160727_2333 (1 squashed migrations) [X]\
+ 0052_auto_fix_realmalias_realm_nullable [X] 0089_auto_20170710_1353")
+# We check if there is any new migration with the 'auto' keyword in its name and
+# cause a error to rename to a more meaningful name
+if [ "$auto_named_migrations" != "$already_auto_named_migrations" ]; then
+    echo 'ERROR: It seems like one or more of the newly created migrations contain the "auto" keyword in their name.'
+    echo 'We prefer our migrations to have meaningful names rather than the auto generated names.'
+    echo 'Maybe rename the migration with a more meaningful name?'
+    echo
+    exit 1
+fi
+
 if ! ./manage.py makemigrations --check --dry-run; then
     echo
     echo 'ERROR: Migrations are not consistent with models!  Fix with `./tools/renumber-migrations`.'
